### PR TITLE
Added type definitions for typescript

### PR DESCRIPTION
**Pull request by lekoaf**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Added typescript definitions to this library.

**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Review by feross — APPROVED** [review]

**Comment by feross** [comment]
Doesn't there also need to be a `"types"` key in `package.json`?

**Comment by lekoaf** [comment]
> Doesn't there also need to be a `"types"` key in `package.json`?

Oh, maybe. I'll look in to it.

**Comment by feross** [comment]
Looks like it's advisable: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package

**Comment by lekoaf** [comment]
Fixed!

**Review by feross — APPROVED** [review]

**Pull request merged**
